inherit_from: .rubocop_todo.yml

require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Include:
    - 'lib/**/*'
  Exclude:
    - '**/*.xsd'
    - '.git/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/ModuleFunction:
  EnforcedStyle: extend_self

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/RaiseArgs:
  EnforcedStyle: compact
