inherit_from: .rubocop_todo.yml

require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Include:
    - 'lib/**/*'
  Exclude:
    - '**/*.xsd'
    - '.git/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Metrics/AbcSize:
  Max: 200

Metrics/BlockLength:
  Max: 100

Metrics/ClassLength:
  Max: 1000

Metrics/CyclomaticComplexity:
  Max: 30

Metrics/MethodLength:
  Max: 100

Metrics/ModuleLength:
  Max: 1000

Metrics/PerceivedComplexity:
  Max: 30

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/ModuleFunction:
  EnforcedStyle: extend_self

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/RaiseArgs:
  EnforcedStyle: compact
