language: ruby
bundler_args: --jobs 4 --retry 3
rvm:
- 2.0.0-p647
- 2.1.7
- 2.2.3
- jruby-1.7.22
- jruby-9.0.1.0
cache: bundler
sudo: false
before_script:
- "gem install bundler-audit --no-rdoc --no-ri && bundle-audit update"
script:
- bundle-audit
- bundle exec rake license_finder
- bundle exec rake test
